
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Langrisser
{
    /// <summary>
    /// 单例配置
    /// </summary>
    [Config]
    public partial class InstanceBean : BeanBase
    {
        public virtual void LoadData(JSONNode buf)
        {
            { if(!buf["id"].IsNumber) { throw new SerializationException(); }  Id = buf["id"]; }
            IdRef = default;
        }
    
        public static InstanceBean DeserializeInstanceBean(JSONNode buf)
        {
            var obj = new InstanceBean();
            obj.LoadData(buf);
            return obj;
        }
    
        /// <summary>
        /// id
        /// </summary>
        [ConfigField]
        [OriginalFieldName("id")]
        public int Id;
    
        public ClassBean IdRef;
        public const int TypeID = -573891067;
        public override int GetTypeId() => TypeID;
    
        public  void ResolveRef()
        {
            IdRef = Tables.MapTable.GetOrDefault(Id);
        }
    
        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "}";
        }
    }
}
