
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using System.Collections.Generic;

namespace Langrisser
{
    [ConfigFilePath("CSV/测试.csv")]
    public partial class ListTable : TableBase
    {
        private readonly List<ClassBean> _dataList;
        private readonly Dictionary<long, List<ClassBean>> _dataMapLongField = new();
    
        public void LoadData(JSONNode buf)
        {
            _dataList.Clear();
            _dataMapLongField.Clear();
            
            foreach(JSONNode ele in buf.Children)
            {
                ClassBean v;
                { if(!ele.IsObject) { throw new SerializationException(); }  v = ClassBean.DeserializeClassBean(ele);  }
                if(!_dataMapLongField.TryGetValue(v.LongField,out var longFieldList))
                {
                    longFieldList = new();
                    _dataMapLongField.Add(v.LongField,longFieldList);
                }
                longFieldList.Add(v);
                _dataList.Add(v);
            }
        }
    
        public List<ClassBean> DataList => _dataList;
        public List<ClassBean> GetListByLongField(long key) => _dataMapLongField.GetValueOrDefault(key);
       
        public void ResolveRef()
        {
            foreach(var v in _dataList)
            {
                v.ResolveRef();
            }
        }
    }
}
