
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using System.Collections.Generic;

namespace Langrisser
{
    [ConfigFilePath("CSV/测试.csv")]
    public partial class MapTable : TableBase
    {
        private readonly Dictionary<int, ClassBean> _dataMap = new();
        private readonly List<ClassBean> _dataList = new();
        
        public void LoadData(JSONNode buf)
        {
            _dataList.Clear();
            
            foreach(JSONNode ele in buf.Children)
            {
                ClassBean v;
                
                int key;
                { if(!ele["intField"].IsNumber) { throw new SerializationException(); }  key = ele["intField"]; }
                if(_dataMap.TryGetValue(key,out v))
                {
                    v.LoadData(ele);
                }
                else
                {
                    { if(!ele.IsObject) { throw new SerializationException(); }  v = ClassBean.DeserializeClassBean(ele);  }
                    _dataMap.Add(v.IntField, v);
                }
    
                _dataList.Add(v);
            }
        }
    
        public Dictionary<int, ClassBean> DataMap => _dataMap;
        public List<ClassBean> DataList => _dataList;
    
        public ClassBean GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ClassBean Get(int key) => _dataMap[key];
        public ClassBean this[int key] => _dataMap[key];
    
        public void ResolveRef()
        {
            foreach(var v in _dataList)
            {
                v.ResolveRef();
            }
        }
        
        public override void PreExport()
        {
            DataList.Clear();
            DataList.AddRange(DataMap.Values);
            DataList.Sort((a,b)=>a.IntField.CompareTo(b.IntField));
        }
        
        public override List<object> GetConfigList()
        {
            List<object> configs = new();
            configs.AddRange(DataList.OfType<object>());
            return configs;
        }  
    }
}
