
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using System.Collections.Generic;

namespace Langrisser
{
    [ConfigFilePath("CSV/单例测试.csv")]
    public partial class OneTable : TableBase
    {
    
        private ValueBean _data;
    
        public void LoadData(JSONNode buf)
        {
            int n = buf.Count;
            if (n != 1) 
            {
                throw new SerializationException("table mode=one, but size != 1");
            }
            _data.LoadData(buf[0]);
        }
    
        /// <summary>
        /// id
        /// </summary>
        public int Id => _data.Id;
        
        public void ResolveRef()
        {
            _data.ResolveRef();
        }
    }
}
