
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
#if UNITY_EDITOR
using UnityEngine;
#endif

namespace Langrisser
{
    /// <summary>
    /// 语言类型
    /// </summary>
    public enum TestEnumType
    {
        /// <summary>
        /// 测试枚举
        /// </summary>
        [EnumAlias("测试枚举1")]
#if UNITY_EDITOR
        [InspectorName("测试枚举1")]
#endif
        Enum1 = 2,
        /// <summary>
        /// 测试枚举
        /// </summary>
        [EnumAlias("测试枚举2")]
#if UNITY_EDITOR
        [InspectorName("测试枚举2")]
#endif
        Enum2 = 3,
        /// <summary>
        /// 测试枚举
        /// </summary>
        [EnumAlias("测试枚举3")]
#if UNITY_EDITOR
        [InspectorName("测试枚举3")]
#endif
        Enum3 = 4,
        /// <summary>
        /// 测试枚举
        /// </summary>
        [EnumAlias("测试枚举4")]
#if UNITY_EDITOR
        [InspectorName("测试枚举4")]
#endif
        Enum4 = 5,
    }
}
