
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using System.Collections.Generic;

namespace Langrisser
{
    [ConfigFilePath("CSV/测试.csv")]
    public partial class UnionIndexListTable : TableBase
    {
        private readonly List<ClassBean> _dataList;
        private readonly Dictionary<long, List<ClassBean>> _dataMapLongField = new();
        private Dictionary<(int, long), ClassBean> _dataMapUnion;
    
        public void LoadData(JSONNode buf)
        {
            _dataList.Clear();
            _dataMapLongField.Clear();
            
            foreach(JSONNode ele in buf.Children)
            {
                ClassBean v;
                
                int intField;
                { if(!ele["intField"].IsNumber) { throw new SerializationException(); }  intField = ele["intField"]; }
                
                int longField;
                { if(!ele["longField"].IsNumber) { throw new SerializationException(); }  longField = ele["longField"]; }
                var key = (
                    intField,
                    longField                
                );
    
                if(_dataMapUnion.TryGetValue(key,out v))
                {             
                    v.LoadData(ele);
                }
                else
                {
                    { if(!ele.IsObject) { throw new SerializationException(); }  v = ClassBean.DeserializeClassBean(ele);  }
                    _dataMapUnion.Add(key, v);
                }
                if(!_dataMapLongField.TryGetValue(v.LongField,out var longFieldList))
                {
                    longFieldList = new();
                    _dataMapLongField.Add(v.LongField,longFieldList);
                }
                longFieldList.Add(v);
                _dataList.Add(v);
            }
        }
    
        public List<ClassBean> DataList => _dataList;
        public List<ClassBean> GetListByLongField(long key) => _dataMapLongField.GetValueOrDefault(key);
        public ClassBean Get(int intField, long longField) => _dataMapUnion.GetValueOrDefault((intField, longField));
       
        public void ResolveRef()
        {
            foreach(var v in _dataList)
            {
                v.ResolveRef();
            }
        }
    }
}
