
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Langrisser
{
    /// <summary>
    /// 值类型
    /// </summary>
    [Config]
    public partial struct ValueBean
    {
        public void LoadData(JSONNode buf)
        {
            { if(!buf["id"].IsNumber) { throw new SerializationException(); }  Id = buf["id"]; }
        }
    
        public static ValueBean DeserializeValueBean(JSONNode buf)
        {
            var obj = new ValueBean();
            obj.LoadData(buf);
            return obj;
        }
    
        /// <summary>
        /// id
        /// </summary>
        [ConfigField]
        [OriginalFieldName("id")]
        public int Id;
    
    
        public  void ResolveRef()
        {
        }
    
        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "}";
        }
    }
}
